version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3050:3000
    volumes:
      - ./frontend:/app
  backend:
    build: ./backend
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
    environment:
      DB_URL: mongodb://database/vidly
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
volumes:
  vidly:
